function vhandling ( theVehicle )
    if getElementModel(theVehicle) == 451 then -------------- vehicle Id
        setVehicleHandling(theVehicle, "mass", 1400.0)
		setVehicleHandling(theVehicle, "turnMass", 3000)
		setVehicleHandling(theVehicle, "dragCoeff", 2.0 )
		setVehicleHandling(theVehicle, "centerOfMass", { 0.0,0.0,-0.30 } )
		setVehicleHandling(theVehicle, "percentSubmerged", 85)
		setVehicleHandling(theVehicle, "tractionMultiplier", 0.65)
		setVehicleHandling(theVehicle, "tractionLoss", 0.90)
		setVehicleHandling(theVehicle, "tractionBias", 0.50)
		setVehicleHandling(theVehicle, "numberOfGears", 5)
		setVehicleHandling(theVehicle, "maxVelocity", 200.0)
		setVehicleHandling(theVehicle, "engineAcceleration", 11.2 )
		setVehicleHandling(theVehicle, "engineInertia", 10.0)
		setVehicleHandling(theVehicle, "driveType", "fwd")
		setVehicleHandling(theVehicle, "engineType", "petrol")
		setVehicleHandling(theVehicle, "brakeDeceleration", 11.0)
		setVehicleHandling(theVehicle, "brakeBias", 0.45)
		setVehicleHandling(theVehicle, "steeringLock",  30.0 )
		setVehicleHandling(theVehicle, "suspensionForceLevel", 1.80)
		setVehicleHandling(theVehicle, "suspensionDamping", 0.20 )
		setVehicleHandling(theVehicle, "suspensionHighSpeedDamping", 0.0)
		setVehicleHandling(theVehicle, "suspensionUpperLimit", 0.28 )
		setVehicleHandling(theVehicle, "suspensionLowerLimit", -0.15)
		setVehicleHandling(theVehicle, "suspensionFrontRearBias", 0.5 )
		setVehicleHandling(theVehicle, "suspensionAntiDiveMultiplier", 0.4)
		setVehicleHandling(theVehicle, "seatOffsetDistance", 0.25)
		setVehicleHandling(theVehicle, "collisionDamageMultiplier", 0.5)
		setVehicleHandling(theVehicle, "modelFlags", 0x40002800)
		setVehicleHandling(theVehicle, "handlingFlags", 0x00400002)
    end
end
addEventHandler ( "onPlayerVehicleEnter", getRootElement(), vhandling )