object64 = getElementByID("object64")
object65 = getElementByID("object65")
object66 = getElementByID("object66")
object67 = getElementByID("object67")
object68 = getElementByID("object68")
object69 = getElementByID("object69")
object70 = getElementByID("object70")
object71 = getElementByID("object71")
object72 = getElementByID("object72")
object73 = getElementByID("object73")
object74 = getElementByID("object74")
object75 = getElementByID("object75")
object76 = getElementByID("object76")
object77 = getElementByID("object77")
object78 = getElementByID("object78")
object79 = getElementByID("object79")
object80 = getElementByID("object80")
object81 = getElementByID("object81")
object82 = getElementByID("object82")
object83 = getElementByID("object83")
object84 = getElementByID("object84")
object85 = getElementByID("object85")
object100 = getElementByID("object100")
object101 = getElementByID("object101")
object103 = getElementByID("object103")
object108 = getElementByID("object108")
object109 = getElementByID("object109")
object110 = getElementByID("object110")
object111 = getElementByID("object111")
object115 = getElementByID("object115")
object116 = getElementByID("object116")
object117 = getElementByID("object117")
object118 = getElementByID("object118")
object121 = getElementByID("object121")
object122 = getElementByID("object122")
object159 = getElementByID("object159")
object160 = getElementByID("object160")
object161 = getElementByID("object161")
object162 = getElementByID("object162")
object174 = getElementByID("object174")
object175 = getElementByID("object175")
object176 = getElementByID("object176")
object177 = getElementByID("object177")
object178 = getElementByID("object178")
object179 = getElementByID("object179")
object180 = getElementByID("object180")
object181 = getElementByID("object181")
object182 = getElementByID("object182")
object183 = getElementByID("object183")
object184 = getElementByID("object184")
object185 = getElementByID("object185")
object186 = getElementByID("object186")

function toggleCrucialObjectBreak()
	setObjectBreakable(object64, false)
	setObjectBreakable(object65, false)
	setObjectBreakable(object66, false)
	setObjectBreakable(object67, false)
	setObjectBreakable(object68, false)
	setObjectBreakable(object69, false)
	setObjectBreakable(object70, false)
	setObjectBreakable(object71, false)
	setObjectBreakable(object72, false)
	setObjectBreakable(object73, false)
	setObjectBreakable(object74, false)
	setObjectBreakable(object75, false)
	setObjectBreakable(object76, false)
	setObjectBreakable(object77, false)
	setObjectBreakable(object78, false)
	setObjectBreakable(object79, false)
	setObjectBreakable(object80, false)
	setObjectBreakable(object81, false)
	setObjectBreakable(object82, false)
	setObjectBreakable(object83, false)
	setObjectBreakable(object84, false)
	setObjectBreakable(object85, false)
	setObjectBreakable(object100, false)
	setObjectBreakable(object101, false)
	setObjectBreakable(object103, false)
	setObjectBreakable(object108, false)
	setObjectBreakable(object109, false)
	setObjectBreakable(object110, false)
	setObjectBreakable(object111, false)
	setObjectBreakable(object115, false)
	setObjectBreakable(object116, false)
	setObjectBreakable(object117, false)
	setObjectBreakable(object118, false)
	setObjectBreakable(object121, false)
	setObjectBreakable(object122, false)
	setObjectBreakable(object159, false)
	setObjectBreakable(object160, false)
	setObjectBreakable(object161, false)
	setObjectBreakable(object162, false)
	setObjectBreakable(object174, false)
	setObjectBreakable(object175, false)
	setObjectBreakable(object176, false)
	setObjectBreakable(object177, false)
	setObjectBreakable(object178, false)
	setObjectBreakable(object179, false)
	setObjectBreakable(object180, false)
	setObjectBreakable(object181, false)
	setObjectBreakable(object182, false)
	setObjectBreakable(object183, false)
	setObjectBreakable(object184, false)
	setObjectBreakable(object185, false)
	setObjectBreakable(object186, false)
end
addEventHandler("onClientResourceStart", resourceRoot, toggleCrucialObjectBreak)
